name: Website Audit

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Packages
        run: npm install

      - name: Run Audit Script
        run: node audit.js
        env:
          SITE_URL: https://www.amazon.in/

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: website-audit-report
          path: report.html
